import = [
    "/home/artty/.config/alacritty/themes/themes/rose-pine.toml",
    # "/home/artty/.config/alacritty/themes/themes/catppuccin-mocha.toml",
    # "/home/artty/.config/alacritty/themes/themes/monokai_charcoal.toml",
    # "/home/artty/.config/alacritty/themes/themes/iterm.toml",
    # "/home/artty/.config/alacritty/themes/themes/dracula.toml",
    # "/home/artty/.config/alacritty/themes/themes/snazzy.toml",

    # "/home/artty/.config/alacritty/fonts/cascadia.toml"
    "/home/artty/.config/alacritty/fonts/sourcecodepro.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
padding = {x = 2, y = 0}
