[font]
size = 10

[font.bold]
family = "SourceCodePro"
style = "Semibold"

[font.bold_italic]
family = "SourceCodePro"
style = "SemiboldIt"

[font.italic]
family = "SourceCodePro"
style = "Italic"

[font.normal]
family = "SourceCodePro"
style = "Semibold"
