[font]
size = 15

[font.bold]
family = "SourceCodePro"
style = "Semibold"

[font.bold_italic]
family = "SourceCodePro"
style = "SemiboldIt"

[font.italic]
family = "SourceCodePro"
style = "MediumIt"

[font.normal]
family = "SourceCodePro"
style = "Medium"
