[General]
EnableNetworkConfiguration=true

ManagementFrameProtection=1

[Network]
NameResolvingService=systemd

[Settings]
AutoConnect=true
AddressRandomization=network
AlwaysRandomizeAddress=true

[Scan]
DisableRoamingScan=true
